apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gratefultolord/zadanie-6105:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_ADDRESS
          value: "0.0.0.0:8080"
        - name: POSTGRES_CONN
          value: "postgres://cnrprod1725726396-team-78921:cnrprod1725726396-team-78921@rc1b-5xmqy6bq501kls4m.mdb.yandexcloud.net:6432/cnrprod1725726396-team-78921"
        - name: POSTGRES_USERNAME
          value: "cnrprod1725726396-team-78921"
        - name: POSTGRES_PASSWORD
          value: "cnrprod1725726396-team-78921"
        - name: POSTGRES_HOST
          value: "rc1b-5xmqy6bq501kls4m.mdb.yandexcloud.net"
        - name: POSTGRES_PORT
          value: "6432"
        - name: POSTGRES_DATABASE
          value: "cnrprod1725726396-team-78921"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
      restartPolicy: Always

